mod_type = language
mod_name = FR - Règles grammaticales - TEST
mod_description = Règles françaises de test pour Rebuild 3 Android
mod_language_name = Français
mod_locale_id = FR

rule_he_male = il
rule_he_female = elle
rule_him_male = lui
rule_him_female = elle
rule_his_male = son
rule_his_female = son
rule_hiss_male = le sien
rule_hiss_female = le sien
rule_himself_male = lui-même
rule_himself_female = elle-même
rule_guy_male = homme
rule_guy_female = femme
rule_man_male = homme
rule_man_female = femme
rule_dude_male = gars
rule_dude_female = fille
rule_boy_male = garçon
rule_boy_female = fille
rule_bastard_male = salaud
rule_bastard_female = salope
rule_daddy_male = papa
rule_daddy_female = maman
rule_brother_male = frère
rule_brother_female = sœur
rule_son_male = fils
rule_son_female = fille
rule_husband_male = mari
rule_husband_female = femme
rule_sir_male = monsieur
rule_sir_female = madame
rule_mister_male = monsieur
rule_mister_female = mademoiselle
rule_we_plural = nous
rule_we_singular = je
rule_us_plural = nous
rule_us_singular = moi
rule_our_plural = notre
rule_our_singular = mon
rule_ours_plural = le nôtre
rule_ours_singular = le mien
rule_ourselves_plural = nous-mêmes
rule_ourselves_singular = moi-même
rule_are_plural = sommes
rule_are_singular = suis
rule_were_plural = étions
rule_were_singular = étais
rule_weren't_plural = n'étions pas
rule_weren't_singular = n'étais pas
rule_we're_plural = nous sommes
rule_we're_singular = je suis
rule_we'll_plural = nous allons
rule_we'll_singular = je vais
rule_we've_plural = nous avons
rule_we've_singular = j'ai
