mod_type = language
mod_name = FR - Ressources - TEST
mod_description = Traduction française de test pour Rebuild 3 Android
mod_language_name = Français
mod_locale_id = FR

resource_food_resourceName = Nourriture
resource_food_resourceInfo = Ça se mange
resource_materials_resourceName = Matériaux
resource_materials_resourceInfo = Matériaux de construction nécessaires pour bâtir et reconquérir des bâtiments
resource_ammo_resourceName = Munitions
resource_ammo_resourceInfo = Utilisées automatiquement chaque fois que quelqu'un tire avec une arme
resource_fuel_resourceName = Carburant
resource_fuel_resourceInfo = Utilisé pour alimenter les véhicules et certains bâtiments spéciaux
resource_medicine_resourceName = Médicaments
resource_medicine_resourceInfo = Utilisés pour soigner les survivants
resource_bombs_resourceName = Explosifs
resource_bombs_resourceInfo = Tue instantanément tous les zombies présents dans un bâtiment
resource_bombs_confirmText = Choisissez un bâtiment contenant des zombies à faire exploser
resource_bombs_resultTitle = Kaa-boum !
resource_bombs_resultText = On a envoyé ces zombies en enfer !
resource_attractors_resourceName = Appât à zombies
resource_attractors_resourceInfo = Attire progressivement les zombies des bâtiments voisins
resource_attractors_confirmText = Choisissez un endroit où installer l'appât à zombies
resource_attractors_resultTitle = Appât à zombies installé
resource_medkits_resourceName = Kits de soins
resource_medkits_resourceInfo = Soigne instantanément un survivant blessé
resource_medkits_confirmText = Choisissez un survivant blessé à soigner
resource_medkits_resultTitle = Guérison miraculeuse
resource_medkits_resultText = Nous avons remis [Name] sur pied grâce à l'un de nos kits de soins.
resource_traps_resourceName = Pièges à zombies
resource_traps_resourceInfo = Tue progressivement les zombies présents dans un bâtiment
resource_traps_confirmText = Choisissez un endroit où installer un piège à zombies
resource_traps_resultTitle = Piège installé
resource_fireworks_resourceName = Feux d'artifice
resource_fireworks_resourceInfo = Améliore instantanément le moral des survivants
resource_fireworks_confirmText = Êtes-vous sûr de vouloir allumer tout ça ?
resource_fireworks_resultTitle = Feux d'artifice !
resource_bathsalts_resourceName = Sels de bain
resource_bathsalts_resourceInfo = Utilisés comme des munitions pour rendre les soldats plus heureux et plus efficaces
resource_cure_resourceName = Doses de vaccin
resource_cure_resourceInfo = Les nouveaux survivants seront automatiquement immunisés
